# Generated by Django 3.2.9 on 2021-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_company',
        ),
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.CharField(max_length=64, null=True, verbose_name='Компания пользователя'),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.EmailField(default='Ivan@mail.ru', max_length=254, primary_key=True, serialize=False, verbose_name='Имя пользователя'),
        ),
    ]
