# Generated by Django 3.2.9 on 2021-11-12 13:07

from django.db import migrations


def populate(apps, schema_editor):
    Tender = apps.get_model('tenders', 'Tenders')
    Tender.objects.all().update(price=1234567)


class Migration(migrations.Migration):
    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
