# Generated by Django 3.2.9 on 2021-11-15 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0003_rename_company_tenders_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenders',
            name='user_email',
        ),
        migrations.AddField(
            model_name='tenders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
